"""fix animal table

Revision ID: b10d94c4c8a7
Revises: 147365f423cb
Create Date: 2025-02-28 15:59:28.009522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10d94c4c8a7'
down_revision: Union[str, None] = '147365f423cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('health_condition', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('current_weight', sa.String(), nullable=False))
    op.add_column('animal', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('animal', 'createdAt')
    op.drop_column('animal', 'healthCondition')
    op.drop_column('animal', 'currentWeight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('currentWeight', sa.VARCHAR(), nullable=False))
    op.add_column('animal', sa.Column('healthCondition', sa.VARCHAR(), nullable=True))
    op.add_column('animal', sa.Column('createdAt', sa.DATETIME(), nullable=False))
    op.drop_column('animal', 'created_at')
    op.drop_column('animal', 'current_weight')
    op.drop_column('animal', 'health_condition')
    # ### end Alembic commands ###
