"""feat image_url: Mapped[str] = mapped_column(nullable=True)

Revision ID: d4eed0055ed4
Revises: f2e0bd15ad90
Create Date: 2025-02-28 23:50:15.540624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4eed0055ed4'
down_revision: Union[str, None] = 'f2e0bd15ad90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('history', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('history', 'imageUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('imageUrl', sa.VARCHAR(), nullable=True))
    op.drop_column('history', 'image_url')
    op.drop_column('animal', 'image_url')
    # ### end Alembic commands ###
